name: Lint and Build

# Run this workflow on push or pull request events on the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Set the version of Node.js

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Build the app
        run: npm run build
